# Loader metadata
modLoader = "javafml"
loaderVersion = "[4,)"
license = "MIT"
issueTrackerURL = "https://github.com/eerussianguy/Entity-Zoning-Supervisor/issues"

# EZS
[[mods]]
    modId = "${modId}"
    version = "${modVersion}"
    displayName = "EZ Supervisor"
    credits = "EERussianguy"
    authors = "EERussianguy"
    description = '''A mod to let you control the destiny of mobs.'''

# Dependencies
[[dependencies.ez_supervisor]]
    modId = "tfc"
    type = "optional"
    versionRange = "${tfcVersionRange}"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.ez_supervisor]]
    modId = "neoforge"
    type = "required"
    versionRange = "${neoForgeVersionRange}"
    ordering = "AFTER"
    side = "BOTH"

[[dependencies.ez_supervisor]]
    modId = "minecraft"
    type = "required"
    versionRange = "${minecraftVersionRange}"
    ordering = "AFTER"
    side = "BOTH"

[[mixins]]
    config = "${modId}.mixins.json"

# We do our own biome coloring, see #2279
[mods."sodium:options"]
    "mixin.features.fast_biome_colors"=false  # Rubidium
    "mixin.features.render.world.sky"=false  # Embeddium, probably Sodium as well
